In [1]:
import numpy as np
import torch

from checkpoint_manager_v2 import CheckpointManager

queries = CheckpointManager.load('queries', 2)
queries[-1]

"SELECT _id FROM datasets.austin_bikes_1000 WHERE end_latitude BETWEEN 30.249181709840407 AND 30.27569798322769 AND end_longitude BETWEEN -97.76094979393284 AND -97.7237120116757 AND end_station_name IN ('Pfluger Bridge @ W 2nd Street' , 'State Capitol @ 14th & Colorado' , 'East 2nd & Pedernales' , 'South Congress & Elizabeth' , 'Lavaca & 6th' , 'Capitol Station / Congress & 11th' , 'City Hall / Lavaca & 2nd' , '2nd & Congress' , 'MoPac Pedestrian Bridge @ Veterans Drive' , '5th & San Marcos' , 'State Parking Garage @ Brazos & 18th' , 'ACC - West & 12th Street' , 'Boardwalk West' , 'Red River & 8th Street' , 'Davis at Rainey Street' , 'Zilker Park West' , '3rd & West' , 'Republic Square' , 'Waller & 6th St.' , '17th & Guadalupe' , 'Republic Square @ Federal Courthouse Plaza' , 'Capital Metro HQ - East 5th at Broadway' , 'East 4th & Chicon' , 'Toomey Rd @ South Lamar' , 'Guadalupe & 21st' , 'Rainey @ River St' , 'Palmer Auditorium' , 'South Congress & Academy' , 'San Jacinto & 8th Stree

In [2]:
from nn_sampler import RelationalDataset

dataset = RelationalDataset(queries, [*range(0, 100)])

Starting dataset initialization


  0%|          | 11/12570 [00:00<02:02, 102.42it/s]

Connecting to the mysql database...
Connected to localhost:datasets.


100%|██████████| 12570/12570 [00:36<00:00, 340.56it/s]


Elapsed time: 37.0121 seconds


In [13]:
import numpy as np
a = np.array([1,2,3,1])
a_copy = np.copy(a)
a_copy[np.where(a <= 1)] = 0.
a_copy

array([0, 2, 3, 0])

In [20]:
scores = np.array([2,4,0,3,1,5])
k=3
top_k_ind = np.argpartition(-scores, -k)[-k:]
top_k_scores = scores[top_k_ind]
top_k_scores

array([2, 1, 0])

In [1]:
from checkpoint_manager_v2 import CheckpointManager
from nn_sampler import NNSampler

queries = CheckpointManager.load('queries', 3)
# results = CheckpointManager.load('results', 3, numpy=True)
nn_sampler = NNSampler(queries, None)
nn_sampler.fit()

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


Connecting to the mysql database...
Connected to localhost:datasets.
Saving checkpoint nn_sample_train_test.pkl to: [./checkpoints/3]
Starting dataset initialization


100%|██████████| 100/100 [00:00<00:00, 264.72it/s]


Saving checkpoint results.pkl to: [./checkpoints/3]



  | Name  | Type       | Params
-------------------------------------
0 | model | Sequential | 45    
-------------------------------------
45        Trainable params
0         Non-trainable params
45        Total params
0.000     Total estimated model params size (MB)


Elapsed time: 2.8038 seconds


Training: 0it [00:00, ?it/s]

`Trainer.fit` stopped: `max_epochs=1` reached.


In [1]:
from checkpoint_manager_v2 import CheckpointManager
from nn_sampler import NNSampler

queries = CheckpointManager.load('queries', 3)
results = CheckpointManager.load('results', 3)
nn_sampler2 = NNSampler(queries, results, checkpoint_path='./checkpoints/3/nn_sample_model.ckpt')

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


Connecting to the mysql database...
Connected to localhost:datasets.


In [2]:
from checkpoint_manager_v2 import CheckpointManager

test_ids = CheckpointManager.load('nn_sample_train_test', 3)[1]
ids, losses = nn_sampler2.get_test_error(test_ids, 100)
sum(losses) / len(losses)

Starting dataset initialization
Elapsed time: 0.3544 seconds


0.17

In [3]:
nn_sampler2.get_sample(10)

100%|██████████| 100/100 [00:01<00:00, 67.26it/s]

Saving checkpoint nn_sample.pkl to: [./checkpoints/3]


array([ 83, 167, 689, 606, 514, 416, 424, 664, 194, 461])

In [10]:
import numpy as np

np.argmin(np.array([2,1,1,0,0]))

3

In [14]:
import numpy as np
from scipy.spatial.distance import squareform

data = np.load('./checkpoints/3/triu_distance_matrix.npz')
key = [*data.keys()][0]
dist_matrix = squareform(data[key])
dist_matrix

array([[0.        , 0.4367599 , 0.45355706, ..., 0.43876847, 0.48539486,
        0.47708749],
       [0.4367599 , 0.        , 0.45169225, ..., 0.42265785, 0.47914486,
        0.46151231],
       [0.45355706, 0.45169225, 0.        , ..., 0.45346558, 0.46775743,
        0.44658276],
       ...,
       [0.43876847, 0.42265785, 0.45346558, ..., 0.        , 0.48448928,
        0.47498787],
       [0.48539486, 0.47914486, 0.46775743, ..., 0.48448928, 0.        ,
        0.45218615],
       [0.47708749, 0.46151231, 0.44658276, ..., 0.47498787, 0.45218615,
        0.        ]])

In [19]:
np.min(dist_matrix[[0,1,2,3,4,5,6,7,8,9],:][:,[0,3,4,5]], axis=1)

array([0.        , 0.4367599 , 0.43037398, 0.        , 0.        ,
       0.        , 0.52722875, 0.46168968, 0.45129201, 0.43799195])